In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('data.csv')
data.head()

,trans_date_trans_time,credit_card_number,merchant,category,amount,first_name,last_name,gender,street,city,...,latitude,longitude,city_population,job,day_of_birth,trans_number,unix_time,merchant_lat,merchant_long,fraud
0,2/1/2021 0:02,4.750000e+12,fraud_Kling-Grant,grocery_net,19.46,Carrie,Washington,F,6114 Adams Harbor Suite 096,Kingsford Heights,...,41.4802,-86.6919,1423,"Psychologist, forensic",10/7/1998,0442179ed2d64942bc45c5442c3d5895,1328054544,41.587290,-87.582956,0
1,2/1/2021 0:03,4.330000e+15,fraud_Huel-Langworth,misc_net,13.01,Scott,Martin,M,7483 Navarro Flats,Freedom,...,43.0172,-111.0292,471,"Education officer, museum",8/2/1967,ef5b8cbad64ceecb8d1b81960a49b467,1328054607,42.032369,-111.700448,0
2,2/1/2021 0:05,4.720000e+18,"fraud_Streich, Hansen and Veum",gas_transport,50.02,Robert,Drake,M,463 Willie Estates,Burbank,...,36.6966,-96.7869,471,Sub,3/30/1941,eae42972de9670a3d907035c0594d494,1328054744,36.413203,-95.986495,0
3,2/1/2021 0:06,1.800000e+14,fraud_Johns Inc,entertainment,6.11,Jared,Camacho,M,4257 Perez Mall,Canton,...,40.8027,-81.3739,192805,Building control surveyor,6/30/1963,2832eb7d75a6f04468c3e52b03103090,1328054781,40.576060,-81.529672,0
4,2/1/2021 0:08,4.540000e+18,fraud_Spinka Inc,grocery_net,32.14,Nathan,Mendoza,M,767 Adam Mill Apt. 115,Espanola,...,35.9866,-106.0654,18408,Historic buildings inspector/conservation officer,7/18/1972,345575e8bebaaed20c5ded6694383a3a,1328054900,35.125220,-105.981956,0

In [6]:
data.nunique()

trans_date_trans_time    437161
credit_card_number          320
merchant                    693
category                     14
amount                    47121
first_name                  346
last_name                   478
gender                        2
street                      960
city                        876
state                        51
zip_code                    947
latitude                    945
longitude                   946
city_population             863
job                         491
day_of_birth                945
trans_number             975036
unix_time                958061
merchant_lat             947225
merchant_long            963180
fraud                         2
dtype: int64

In [7]:
data.corr()

,credit_card_number,amount,zip_code,latitude,longitude,city_population,unix_time,merchant_lat,merchant_long,fraud
credit_card_number,1.000000,0.001071,0.040917,-0.059138,-0.047546,-0.009005,0.000932,-0.058792,-0.047497,-0.002074
amount,0.001071,1.000000,0.001763,-0.002338,0.000202,0.005658,-0.000829,-0.002266,0.000186,0.214790
zip_code,0.040917,0.001763,1.000000,-0.113947,-0.910007,0.079070,0.001166,-0.113246,-0.909194,-0.000671
latitude,-0.059138,-0.002338,-0.113947,1.000000,-0.015869,-0.155919,-0.001205,0.993599,-0.015861,0.001180
longitude,-0.047546,0.000202,-0.910007,-0.015869,1.000000,-0.053283,-0.001309,-0.015787,0.999120,0.001922
city_population,-0.009005,0.005658,0.079070,-0.155919,-0.053283,1.000000,-0.000749,-0.155064,-0.053253,0.000820
unix_time,0.000932,-0.000829,0.001166,-0.001205,-0.001309,-0.000749,1.000000,-0.001148,-0.001334,-0.005149
merchant_lat,-0.058792,-0.002266,-0.113246,0.993599,-0.015787,-0.155064,-0.001148,1.000000,-0.015781,0.001037
merchant_long,-0.047497,0.000186,-0.909194,-0.015861,0.999120,-0.053253,-0.001334,-0.015781,1.000000,0.001955
fraud,-0.002074,0.214790,-0.000671,0.001180,0.001922,0.000820,-0.005149,0.001037,0.001955,1.000000

In [8]:

# Calculate the correlation matrix
correlation_matrix = data.corr()

# Check the correlation of other variables with the 'fraud' variable
fraud_correlation = correlation_matrix['fraud']

# Sort the correlation values in descending order
sorted_correlation = fraud_correlation.sort_values(ascending=False)

# Print the correlation values
print(sorted_correlation)

fraud                 1.000000
amount                0.214790
merchant_long         0.001955
longitude             0.001922
latitude              0.001180
merchant_lat          0.001037
city_population       0.000820
zip_code             -0.000671
credit_card_number   -0.002074
unix_time            -0.005149
Name: fraud, dtype: float64